### ISSUE TITLE
sendmail_smarthost has hardcoded port number

### ISSUE THREAD

**Issue by dnmvisser** [OpenConext/Stepup-Deploy#56]
The var  `sendmail_smarthost` implicitly assumes TCP port 25.
This breaks deployments that have that port blocked.
A extra configuration options like `sendmail_smarthost_port` could be introduced, which defaults to 25.

**Comment by pmeulen** [comment]
@dnmvisser Can you have a look at #57 and let me know if that solves the issue for you?
